-- MySQL Script generated by MySQL Workbench
-- Sun Jun 27 18:27:13 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema backend
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema backend
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `backend` DEFAULT CHARACTER SET utf8 ;
USE `backend` ;

-- -----------------------------------------------------
-- Table `backend`.`user_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `backend`.`user_type` ;

CREATE TABLE IF NOT EXISTS `backend`.`user_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `backend`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `backend`.`user` ;

CREATE TABLE IF NOT EXISTS `backend`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_uuid` VARCHAR(45) NOT NULL,
  `user_type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_user_type_idx` (`user_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_user_type`
    FOREIGN KEY (`user_type_id`)
    REFERENCES `backend`.`user_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `backend`.`transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `backend`.`transaction` ;

CREATE TABLE IF NOT EXISTS `backend`.`transaction` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `transaction_uuid` VARCHAR(45) NOT NULL,
  `payer_id` INT NOT NULL,
  `payee_id` INT NOT NULL,
  `value` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_transaction_user1_idx` (`payer_id` ASC) VISIBLE,
  INDEX `fk_transaction_user2_idx` (`payee_id` ASC) VISIBLE,
  CONSTRAINT `fk_transaction_user1`
    FOREIGN KEY (`payer_id`)
    REFERENCES `backend`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_user2`
    FOREIGN KEY (`payee_id`)
    REFERENCES `backend`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `backend`.`wallet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `backend`.`wallet` ;

CREATE TABLE IF NOT EXISTS `backend`.`wallet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_wallet_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_wallet_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `backend`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
